// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sessions.proto

package sessionsproto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on StartSessionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StartSessionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StartSessionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StartSessionRequestMultiError, or nil if none found.
func (m *StartSessionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StartSessionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	if all {
		switch v := interface{}(m.GetDeviceInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StartSessionRequestValidationError{
					field:  "DeviceInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StartSessionRequestValidationError{
					field:  "DeviceInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeviceInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StartSessionRequestValidationError{
				field:  "DeviceInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StartSessionRequestMultiError(errors)
	}

	return nil
}

// StartSessionRequestMultiError is an error wrapping multiple validation
// errors returned by StartSessionRequest.ValidateAll() if the designated
// constraints aren't met.
type StartSessionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StartSessionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StartSessionRequestMultiError) AllErrors() []error { return m }

// StartSessionRequestValidationError is the validation error returned by
// StartSessionRequest.Validate if the designated constraints aren't met.
type StartSessionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartSessionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartSessionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartSessionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartSessionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartSessionRequestValidationError) ErrorName() string {
	return "StartSessionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StartSessionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartSessionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartSessionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartSessionRequestValidationError{}

// Validate checks the field values on DeviceInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DeviceInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeviceInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DeviceInfoMultiError, or
// nil if none found.
func (m *DeviceInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *DeviceInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceType

	// no validation rules for AppType

	// no validation rules for AppVersion

	// no validation rules for Os

	// no validation rules for IpAddr

	if m.DeviceName != nil {
		// no validation rules for DeviceName
	}

	if m.OsVersion != nil {
		// no validation rules for OsVersion
	}

	if m.DeviceModel != nil {
		// no validation rules for DeviceModel
	}

	if len(errors) > 0 {
		return DeviceInfoMultiError(errors)
	}

	return nil
}

// DeviceInfoMultiError is an error wrapping multiple validation errors
// returned by DeviceInfo.ValidateAll() if the designated constraints aren't met.
type DeviceInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeviceInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeviceInfoMultiError) AllErrors() []error { return m }

// DeviceInfoValidationError is the validation error returned by
// DeviceInfo.Validate if the designated constraints aren't met.
type DeviceInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeviceInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeviceInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeviceInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeviceInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeviceInfoValidationError) ErrorName() string { return "DeviceInfoValidationError" }

// Error satisfies the builtin error interface
func (e DeviceInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeviceInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeviceInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeviceInfoValidationError{}

// Validate checks the field values on StartSessionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StartSessionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StartSessionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StartSessionResponseMultiError, or nil if none found.
func (m *StartSessionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StartSessionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionID

	// no validation rules for Message

	if len(errors) > 0 {
		return StartSessionResponseMultiError(errors)
	}

	return nil
}

// StartSessionResponseMultiError is an error wrapping multiple validation
// errors returned by StartSessionResponse.ValidateAll() if the designated
// constraints aren't met.
type StartSessionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StartSessionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StartSessionResponseMultiError) AllErrors() []error { return m }

// StartSessionResponseValidationError is the validation error returned by
// StartSessionResponse.Validate if the designated constraints aren't met.
type StartSessionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StartSessionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StartSessionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StartSessionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StartSessionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StartSessionResponseValidationError) ErrorName() string {
	return "StartSessionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StartSessionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStartSessionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StartSessionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StartSessionResponseValidationError{}
