// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: sessions.proto

package sessionsproto

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	DeviceInfo    string                 `protobuf:"bytes,4,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	ExpiredAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSessionRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateSessionRequest) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *CreateSessionRequest) GetExpiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionData           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSession() *SessionData {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SessionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	DeviceInfo    string                 `protobuf:"bytes,3,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	ExpiredAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionData) Reset() {
	*x = SessionData{}
	mi := &file_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionData) ProtoMessage() {}

func (x *SessionData) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionData.ProtoReflect.Descriptor instead.
func (*SessionData) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *SessionData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionData) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionData) GetDeviceInfo() string {
	if x != nil {
		return x.DeviceInfo
	}
	return ""
}

func (x *SessionData) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *SessionData) GetExpiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *SessionData) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SessionData) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetSessionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionByIdRequest) Reset() {
	*x = GetSessionByIdRequest{}
	mi := &file_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionByIdRequest) ProtoMessage() {}

func (x *GetSessionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetSessionByIdRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSessionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionData           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionByIdResponse) Reset() {
	*x = GetSessionByIdResponse{}
	mi := &file_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionByIdResponse) ProtoMessage() {}

func (x *GetSessionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetSessionByIdResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionByIdResponse) GetSession() *SessionData {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *GetSessionByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *int64                 `protobuf:"varint,1,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	IpAddress     *string                `protobuf:"bytes,2,opt,name=ipAddress,proto3,oneof" json:"ipAddress,omitempty"`
	DeviceInfo    *string                `protobuf:"bytes,3,opt,name=deviceInfo,proto3,oneof" json:"deviceInfo,omitempty"`
	IsActive      *bool                  `protobuf:"varint,4,opt,name=isActive,proto3,oneof" json:"isActive,omitempty"`
	ExpiredAfter  *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=expiredAfter,proto3,oneof" json:"expiredAfter,omitempty"`
	ExpiredBefore *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=expiredBefore,proto3,oneof" json:"expiredBefore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsRequest) Reset() {
	*x = GetSessionsRequest{}
	mi := &file_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsRequest) ProtoMessage() {}

func (x *GetSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsRequest.ProtoReflect.Descriptor instead.
func (*GetSessionsRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *GetSessionsRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *GetSessionsRequest) GetDeviceInfo() string {
	if x != nil && x.DeviceInfo != nil {
		return *x.DeviceInfo
	}
	return ""
}

func (x *GetSessionsRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *GetSessionsRequest) GetExpiredAfter() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredAfter
	}
	return nil
}

func (x *GetSessionsRequest) GetExpiredBefore() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredBefore
	}
	return nil
}

type GetSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionData         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResponse) Reset() {
	*x = GetSessionsResponse{}
	mi := &file_sessions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResponse) ProtoMessage() {}

func (x *GetSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResponse.ProtoReflect.Descriptor instead.
func (*GetSessionsResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionsResponse) GetSessions() []*SessionData {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetSessionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Fields        *UpdateFields          `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_sessions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetFields() *UpdateFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

type UpdateFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     *string                `protobuf:"bytes,1,opt,name=ipAddress,proto3,oneof" json:"ipAddress,omitempty"`
	DeviceInfo    *string                `protobuf:"bytes,2,opt,name=deviceInfo,proto3,oneof" json:"deviceInfo,omitempty"`
	IsActive      *bool                  `protobuf:"varint,3,opt,name=isActive,proto3,oneof" json:"isActive,omitempty"`
	ExpiredAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expiredAt,proto3,oneof" json:"expiredAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFields) Reset() {
	*x = UpdateFields{}
	mi := &file_sessions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFields) ProtoMessage() {}

func (x *UpdateFields) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFields.ProtoReflect.Descriptor instead.
func (*UpdateFields) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFields) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *UpdateFields) GetDeviceInfo() string {
	if x != nil && x.DeviceInfo != nil {
		return *x.DeviceInfo
	}
	return ""
}

func (x *UpdateFields) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateFields) GetExpiredAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionData           `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_sessions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sessions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_sessions_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateSessionResponse) GetSession() *SessionData {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *UpdateSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_sessions_proto protoreflect.FileDescriptor

const file_sessions_proto_rawDesc = "" +
	"\n" +
	"\x0esessions.proto\x12\bsessions\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x14CreateSessionRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tipAddress\x18\x03 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"deviceInfo\x18\x04 \x01(\tR\n" +
	"deviceInfo\x128\n" +
	"\texpiredAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"b\n" +
	"\x15CreateSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.sessions.SessionDataR\asession\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x02\n" +
	"\vSessionData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tipAddress\x18\x02 \x01(\tR\tipAddress\x12\x1e\n" +
	"\n" +
	"deviceInfo\x18\x03 \x01(\tR\n" +
	"deviceInfo\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive\x128\n" +
	"\texpiredAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"'\n" +
	"\x15GetSessionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x16GetSessionByIdResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.sessions.SessionDataR\asession\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfe\x02\n" +
	"\x12GetSessionsRequest\x12\x1b\n" +
	"\x06userId\x18\x01 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12!\n" +
	"\tipAddress\x18\x02 \x01(\tH\x01R\tipAddress\x88\x01\x01\x12#\n" +
	"\n" +
	"deviceInfo\x18\x03 \x01(\tH\x02R\n" +
	"deviceInfo\x88\x01\x01\x12\x1f\n" +
	"\bisActive\x18\x04 \x01(\bH\x03R\bisActive\x88\x01\x01\x12C\n" +
	"\fexpiredAfter\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x04R\fexpiredAfter\x88\x01\x01\x12E\n" +
	"\rexpiredBefore\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x05R\rexpiredBefore\x88\x01\x01B\t\n" +
	"\a_userIdB\f\n" +
	"\n" +
	"_ipAddressB\r\n" +
	"\v_deviceInfoB\v\n" +
	"\t_isActiveB\x0f\n" +
	"\r_expiredAfterB\x10\n" +
	"\x0e_expiredBefore\"b\n" +
	"\x13GetSessionsResponse\x121\n" +
	"\bsessions\x18\x01 \x03(\v2\x15.sessions.SessionDataR\bsessions\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x14UpdateSessionRequest\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12.\n" +
	"\x06fields\x18\x02 \x01(\v2\x16.sessions.UpdateFieldsR\x06fields\"\xee\x01\n" +
	"\fUpdateFields\x12!\n" +
	"\tipAddress\x18\x01 \x01(\tH\x00R\tipAddress\x88\x01\x01\x12#\n" +
	"\n" +
	"deviceInfo\x18\x02 \x01(\tH\x01R\n" +
	"deviceInfo\x88\x01\x01\x12\x1f\n" +
	"\bisActive\x18\x03 \x01(\bH\x02R\bisActive\x88\x01\x01\x12=\n" +
	"\texpiredAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\texpiredAt\x88\x01\x01B\f\n" +
	"\n" +
	"_ipAddressB\r\n" +
	"\v_deviceInfoB\v\n" +
	"\t_isActiveB\f\n" +
	"\n" +
	"_expiredAt\"b\n" +
	"\x15UpdateSessionResponse\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.sessions.SessionDataR\asession\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xde\x02\n" +
	"\x0fSessionsService\x12R\n" +
	"\rCreateSession\x12\x1e.sessions.CreateSessionRequest\x1a\x1f.sessions.CreateSessionResponse\"\x00\x12U\n" +
	"\x0eGetSessionById\x12\x1f.sessions.GetSessionByIdRequest\x1a .sessions.GetSessionByIdResponse\"\x00\x12L\n" +
	"\vGetSessions\x12\x1c.sessions.GetSessionsRequest\x1a\x1d.sessions.GetSessionsResponse\"\x00\x12R\n" +
	"\rUpdateSession\x12\x1e.sessions.UpdateSessionRequest\x1a\x1f.sessions.UpdateSessionResponse\"\x00BlZjgithub.com/EugeneTsydenov/chesshub-user-service/internal/controllers/grpccontroller/genproto;sessionsprotob\x06proto3"

var (
	file_sessions_proto_rawDescOnce sync.Once
	file_sessions_proto_rawDescData []byte
)

func file_sessions_proto_rawDescGZIP() []byte {
	file_sessions_proto_rawDescOnce.Do(func() {
		file_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)))
	})
	return file_sessions_proto_rawDescData
}

var file_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_sessions_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: sessions.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: sessions.CreateSessionResponse
	(*SessionData)(nil),            // 2: sessions.SessionData
	(*GetSessionByIdRequest)(nil),  // 3: sessions.GetSessionByIdRequest
	(*GetSessionByIdResponse)(nil), // 4: sessions.GetSessionByIdResponse
	(*GetSessionsRequest)(nil),     // 5: sessions.GetSessionsRequest
	(*GetSessionsResponse)(nil),    // 6: sessions.GetSessionsResponse
	(*UpdateSessionRequest)(nil),   // 7: sessions.UpdateSessionRequest
	(*UpdateFields)(nil),           // 8: sessions.UpdateFields
	(*UpdateSessionResponse)(nil),  // 9: sessions.UpdateSessionResponse
	(*timestamp.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_sessions_proto_depIdxs = []int32{
	10, // 0: sessions.CreateSessionRequest.expiredAt:type_name -> google.protobuf.Timestamp
	2,  // 1: sessions.CreateSessionResponse.session:type_name -> sessions.SessionData
	10, // 2: sessions.SessionData.expiredAt:type_name -> google.protobuf.Timestamp
	10, // 3: sessions.SessionData.updatedAt:type_name -> google.protobuf.Timestamp
	10, // 4: sessions.SessionData.createdAt:type_name -> google.protobuf.Timestamp
	2,  // 5: sessions.GetSessionByIdResponse.session:type_name -> sessions.SessionData
	10, // 6: sessions.GetSessionsRequest.expiredAfter:type_name -> google.protobuf.Timestamp
	10, // 7: sessions.GetSessionsRequest.expiredBefore:type_name -> google.protobuf.Timestamp
	2,  // 8: sessions.GetSessionsResponse.sessions:type_name -> sessions.SessionData
	8,  // 9: sessions.UpdateSessionRequest.fields:type_name -> sessions.UpdateFields
	10, // 10: sessions.UpdateFields.expiredAt:type_name -> google.protobuf.Timestamp
	2,  // 11: sessions.UpdateSessionResponse.session:type_name -> sessions.SessionData
	0,  // 12: sessions.SessionsService.CreateSession:input_type -> sessions.CreateSessionRequest
	3,  // 13: sessions.SessionsService.GetSessionById:input_type -> sessions.GetSessionByIdRequest
	5,  // 14: sessions.SessionsService.GetSessions:input_type -> sessions.GetSessionsRequest
	7,  // 15: sessions.SessionsService.UpdateSession:input_type -> sessions.UpdateSessionRequest
	1,  // 16: sessions.SessionsService.CreateSession:output_type -> sessions.CreateSessionResponse
	4,  // 17: sessions.SessionsService.GetSessionById:output_type -> sessions.GetSessionByIdResponse
	6,  // 18: sessions.SessionsService.GetSessions:output_type -> sessions.GetSessionsResponse
	9,  // 19: sessions.SessionsService.UpdateSession:output_type -> sessions.UpdateSessionResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sessions_proto_init() }
func file_sessions_proto_init() {
	if File_sessions_proto != nil {
		return
	}
	file_sessions_proto_msgTypes[5].OneofWrappers = []any{}
	file_sessions_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sessions_proto_rawDesc), len(file_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sessions_proto_goTypes,
		DependencyIndexes: file_sessions_proto_depIdxs,
		MessageInfos:      file_sessions_proto_msgTypes,
	}.Build()
	File_sessions_proto = out.File
	file_sessions_proto_goTypes = nil
	file_sessions_proto_depIdxs = nil
}
